# Generated by Django 2.1 on 2019-04-29 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalyear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.FloatField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalyear.Center')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalyear.Farmer')),
            ],
        ),
    ]
