# Generated by Django 2.1 on 2019-05-02 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalyear', '0003_annualpayment_monthlypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='center',
        ),
        migrations.RemoveField(
            model_name='annualpayment',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='farmer',
        ),
        migrations.AlterField(
            model_name='transcation',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
