# Generated by Django 2.1 on 2019-05-03 04:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalyear', '0004_auto_20190502_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transcation',
            new_name='Transaction',
        ),
    ]
