# Generated by Django 2.1 on 2019-05-04 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalyear', '0005_auto_20190503_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
