# Generated by Django 2.1 on 2019-05-07 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalyear', '0006_auto_20190504_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualpayment',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annualpayment',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='annualpayment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
