# Generated by Django 2.1 on 2019-05-02 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalyear', '0004_auto_20190502_1753'),
        ('users', '0002_auto_20190502_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finalyear.Center'),
            preserve_default=False,
        ),
    ]
