# Generated by Django 2.1 on 2019-05-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190503_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finalyear.Center'),
        ),
    ]
