# Generated by Django 2.0.2 on 2018-02-03 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('showing_at', models.DateTimeField(verbose_name='Time and Date movie will be showing')),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
