# Generated by Django 2.0.2 on 2018-02-21 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
